language: python
cache: pip
dist: jammy
python:
    - "3.10"
    - "3.11"
    - "3.12"
env:
    - TORNADO_VERSION=6.5 PYTEST_VERSION=9.0
    - TORNADO_VERSION=6.4 PYTEST_VERSION=8.3
install:
    - pip install tornado~=$TORNADO_VERSION pytest~=$PYTEST_VERSION
    - pip install PyOpenSSL  # used to create a cert for testing
    - pip install -e .
    - pip install coverage coveralls
script:
    - python test/create_cert.py --cert test/testcert.pem
    - coverage run --branch --source pytest_tornado.plugin -m pytest --strict
    - coverage report -m
after_success:
    - coveralls

jobs:
  include:
    - stage: deploy
      python: "3.10"
      deploy:
        provider: pypi
        distributions: sdist bdist_wheel
        user: eugeniy
        password:
          secure: gmpsfekSDT9LuF3XkJK64myhQ6Xg8WyqI/0m5Gnnb+hSrCFGD8/dgtRdLEULuDkFPvL/FsoE2L6XcdKuqaKkqSM3kk4Min8hqGapcfe/OSOkCDaYSUBCXmV2dlbtMTAzHfo3zpueToUelZvblw9y3wXVFWkmr1mf47Q9kUPIgnU=
        on:
          tags: true
